# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jkali/ece385/final_project/mic_eq/mic_eq.srcs/sources_1/ip/cic_compiler_0/cic_compiler_0.xci
# IP: The module: 'cic_compiler_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jkali/ece385/final_project/mic_eq/mic_eq.gen/sources_1/ip/cic_compiler_0/cic_compiler_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cic_compiler_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/jkali/ece385/final_project/mic_eq/mic_eq.srcs/sources_1/ip/cic_compiler_0/cic_compiler_0.xci
# IP: The module: 'cic_compiler_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jkali/ece385/final_project/mic_eq/mic_eq.gen/sources_1/ip/cic_compiler_0/cic_compiler_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cic_compiler_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
